// File generated by FlutterFire CLI
// ignore_for_file: lines_longer_than_80_chars

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpGE-AiAEkFF35opAR1OtyZKZLiYUTTUU',
    appId: '1:930700432812:web:4ace4d1a015b3f39f15609',
    messagingSenderId: '930700432812',
    projectId: 'littlebites-baby-tracker',
    authDomain: 'littlebites-baby-tracker.firebaseapp.com',
    storageBucket: 'littlebites-baby-tracker.firebasestorage.app',
    measurementId: 'G-JQ1TCL7TKV',
  );
}
